version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: justgold_api
    volumes:
      - .:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules
    working_dir: /usr/src/app
    ports:
      - "3000:3000"
    environment:
      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV}
      - MONGO_URI=mongodb://mongo/justgold-db
      - TWILIO_SID=${TWILIO_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_PHONE=${TWILIO_PHONE}
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT}
      - JWT_SECRET=${JWT_SECRET}
      - AWS_REGION=${AWS_REGION}
      - QUEUE_URL=${QUEUE_URL}
      - LOCALSTACK_ENDPOINT=${LOCALSTACK_ENDPOINT}
    command: npm run dev
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:6
    container_name: justgold_mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    container_name: justgold_redis
    ports:
      - "6379:6379"

  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      - SERVICES=sqs,s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - LOCALSTACK_HOST=localhost
    volumes:
      - "./localstack:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  mongo_data: